#include "gpu.h"
#include "log.h"

#include <dxgi1_6.h>
#include <algorithm>

#include "shader_ps.h"  // generated by build.bat from shaders.hlsl
#include "shader_vs.h"

static constexpr UINT kVendorNvidia = 0x10DE;

bool Gpu::Decodes(const VideoInfo& v) const {
    if (!CanHardwareDecode() || !videoDevice) return false;
    const GUID* profile = nullptr;
    if (v.codec == MFVideoFormat_H264) {
        if (v.tenBit) return false;  // no GPU decodes 10-bit H.264
        profile = &D3D11_DECODER_PROFILE_H264_VLD_NOFGT;
    } else if (v.codec == MFVideoFormat_HEVC) {
        profile = v.tenBit ? &D3D11_DECODER_PROFILE_HEVC_VLD_MAIN10 : &D3D11_DECODER_PROFILE_HEVC_VLD_MAIN;
    } else if (v.codec == MFVideoFormat_VP90) {
        profile = v.tenBit ? &D3D11_DECODER_PROFILE_VP9_VLD_10BIT_PROFILE2 : &D3D11_DECODER_PROFILE_VP9_VLD_PROFILE0;
    } else if (v.codec == MFVideoFormat_AV1) {
        profile = &D3D11_DECODER_PROFILE_AV1_VLD_PROFILE0;
    } else if (v.codec == MFVideoFormat_MPEG2) {
        profile = &D3D11_DECODER_PROFILE_MPEG2_VLD;
    } else {
        return true;
    }

    // The profile list first: CheckVideoDecoderFormat on an unlisted profile is an error on some drivers.
    bool listed = false;
    for (UINT i = 0, n = videoDevice->GetVideoDecoderProfileCount(); i < n && !listed; ++i) {
        GUID g{};
        listed = SUCCEEDED(videoDevice->GetVideoDecoderProfile(i, &g)) && g == *profile;
    }
    if (!listed) return false;
    const DXGI_FORMAT format = v.tenBit ? DXGI_FORMAT_P010 : DXGI_FORMAT_NV12;
    BOOL ok = FALSE;
    if (FAILED(videoDevice->CheckVideoDecoderFormat(profile, format, &ok)) || !ok) return false;
    if (!v.width || !v.height) return true;
    // A decoder with no configurations for this frame size can't take it (e.g. 8K on a 4K-only chip).
    D3D11_VIDEO_DECODER_DESC desc{*profile, v.width, v.height, format};
    UINT configs = 0;
    return SUCCEEDED(videoDevice->GetVideoDecoderConfigCount(&desc, &configs)) && configs > 0;
}

bool GpuSet::Init(DecoderPreference pref) {
    Reset();
    pref_ = pref;

    ComPtr<IDXGIFactory1> factory;
    if (FAILED(CreateDXGIFactory1(IID_PPV_ARGS(&factory)))) return false;
    ComPtr<IDXGIFactory6> factory6;
    factory.As(&factory6);  // missing before Windows 10 1803: then plain enumeration order
    const auto order = pref == DecoderPreference::PowerSaving ? DXGI_GPU_PREFERENCE_MINIMUM_POWER
                                                               : DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE;
    // Testing aid: WALLPAPERPLUS_NO_GPU=1 pretends the machine has no GPU (software renderer only).
    const bool hideGpus = GetEnvironmentVariableW(L"WALLPAPERPLUS_NO_GPU", nullptr, 0) > 0;
    for (UINT i = 0; !hideGpus; ++i) {
        ComPtr<IDXGIAdapter1> adapter;
        HRESULT hr = factory6 ? factory6->EnumAdapterByGpuPreference(i, order, IID_PPV_ARGS(&adapter))
                              : factory->EnumAdapters1(i, &adapter);
        if (FAILED(hr)) break;  // DXGI_ERROR_NOT_FOUND after the last one; other errors would repeat forever
        DXGI_ADAPTER_DESC1 desc{};
        adapter->GetDesc1(&desc);
        if (desc.Flags & DXGI_ADAPTER_FLAG_SOFTWARE) continue;  // Microsoft Basic Render Driver: added last below
        Slot s;
        s.adapter = adapter;
        s.name = desc.Description;
        s.vendor = desc.VendorId;
        for (UINT o = 0;; ++o) {
            ComPtr<IDXGIOutput> output;
            if (FAILED(adapter->EnumOutputs(o, &output))) break;
            DXGI_OUTPUT_DESC od{};
            if (SUCCEEDED(output->GetDesc(&od))) s.outputs.push_back(od.Monitor);
        }
        slots_.push_back(std::move(s));
    }
    // Automatic: after the GPU driving the monitor (see NextDecoder), NVIDIA's decoder first; the rest
    // keep the fastest-first order.
    if (pref == DecoderPreference::Auto)
        std::stable_partition(slots_.begin(), slots_.end(), [](const Slot& s) { return s.vendor == kVendorNvidia; });
    Slot software;
    software.name = L"Microsoft software renderer";
    slots_.push_back(std::move(software));

    for (auto& s : slots_)
        Log(L"GPU found: %s%s", s.name.c_str(), s.outputs.empty() ? L"" : L" (drives a monitor)");
    Log(L"Video decoding: %s", pref == DecoderPreference::Cpu           ? L"processor only"
                               : pref == DecoderPreference::PowerSaving ? L"integrated GPU first, then processor"
                                                                        : L"GPU driving the monitor first, then NVIDIA, then other GPUs, then processor");

    // At least one device must work now, or the controller retries later. Tried on a GPU that
    // drives a monitor (awake anyway), then the software renderer, so this check never wakes a
    // laptop's NVIDIA chip and keeps it powered for the session when no video needs it.
    std::lock_guard lock(mutex_);
    for (auto& s : slots_)
        if (s.adapter && !s.outputs.empty() && Open(s)) return true;
    return Open(slots_.back()) != nullptr;
}

void GpuSet::Reset() {
    std::lock_guard lock(mutex_);
    slots_.clear();
}

Gpu* GpuSet::Open(Slot& s) {
    if (s.gpu) return s.gpu.get();
    if (s.failed) return nullptr;

    auto g = std::make_unique<Gpu>();
    g->name = s.name;
    g->vendor = s.vendor;
    g->software = !s.adapter;
    const D3D_FEATURE_LEVEL levels[] = {D3D_FEATURE_LEVEL_11_1, D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_1,
                                        D3D_FEATURE_LEVEL_10_0};
    const UINT flags = D3D11_CREATE_DEVICE_BGRA_SUPPORT;
    auto create = [&](UINT extra) {
        g->device.Reset();
        g->context.Reset();
        return D3D11CreateDevice(s.adapter.Get(), s.adapter ? D3D_DRIVER_TYPE_UNKNOWN : D3D_DRIVER_TYPE_WARP, nullptr,
                                 flags | extra, levels, ARRAYSIZE(levels), D3D11_SDK_VERSION, &g->device, nullptr,
                                 &g->context);
    };
    // Video support is what hardware decoding needs; without it (software renderer, odd drivers)
    // the device can still draw processor-decoded frames.
    HRESULT hr = create(D3D11_CREATE_DEVICE_VIDEO_SUPPORT);
    if (FAILED(hr)) hr = create(0);
    if (FAILED(hr)) {
        Log(L"GPU: can't use %s (0x%08X)", s.name.c_str(), hr);
        s.failed = true;
        return nullptr;
    }

    g->device.As(&g->lock);
    if (g->lock) g->lock->SetMultithreadProtected(TRUE);

    if (SUCCEEDED(g->device.As(&g->videoDevice)) && SUCCEEDED(g->context.As(&g->videoContext))) {
        UINT token = 0;
        if (g->videoDevice->GetVideoDecoderProfileCount() > 0 && SUCCEEDED(MFCreateDXGIDeviceManager(&token, &g->dxgiManager)) &&
            FAILED(g->dxgiManager->ResetDevice(g->device.Get(), token)))
            g->dxgiManager.Reset();
    } else {
        g->videoDevice.Reset();
        g->videoContext.Reset();
    }

    ComPtr<IDXGIDevice> dxgiDevice;
    ComPtr<IDXGIAdapter> adapter;
    g->device.As(&dxgiDevice);
    if (!dxgiDevice || FAILED(dxgiDevice->GetAdapter(&adapter)) || FAILED(adapter->GetParent(IID_PPV_ARGS(&g->factory)))) {
        Log(L"GPU: %s has no DXGI factory", s.name.c_str());
        s.failed = true;
        return nullptr;
    }
    dxgiDevice->SetGPUThreadPriority(-7);  // let games and other apps win when the GPU is busy

    D3D11_SAMPLER_DESC sd{};
    sd.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
    sd.AddressU = sd.AddressV = sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
    sd.MaxLOD = D3D11_FLOAT32_MAX;
    D3D11_RASTERIZER_DESC rd{};
    rd.FillMode = D3D11_FILL_SOLID;
    rd.CullMode = D3D11_CULL_NONE;
    rd.DepthClipEnable = TRUE;
    if (FAILED(g->device->CreateVertexShader(g_vs, sizeof(g_vs), nullptr, &g->vs)) ||
        FAILED(g->device->CreatePixelShader(g_ps, sizeof(g_ps), nullptr, &g->ps)) ||
        FAILED(g->device->CreateSamplerState(&sd, &g->sampler)) ||
        FAILED(g->device->CreateRasterizerState(&rd, &g->raster))) {
        Log(L"GPU: %s can't create its drawing shaders", s.name.c_str());
        s.failed = true;
        return nullptr;
    }

    Log(L"GPU ready: %s (%s)", s.name.c_str(),
        g->software ? L"no usable GPU: drawing on the processor"
        : g->CanHardwareDecode() ? L"hardware video decoder"
                                 : L"no video decoder: draws only");
    s.gpu = std::move(g);
    return s.gpu.get();
}

Gpu* GpuSet::NextDecoder(const VideoInfo& v, HMONITOR monitor, size_t& cursor) {
    if (pref_ == DecoderPreference::Cpu) return nullptr;
    std::lock_guard lock(mutex_);
    // Automatic: the GPU driving this monitor first (awake anyway, and its frames need no copy to
    // another GPU), then the stored ranking. On a PC with one GPU driving every monitor, that's
    // the same order.
    auto drives = [&](const Slot& s) {
        return pref_ == DecoderPreference::Auto && std::find(s.outputs.begin(), s.outputs.end(), monitor) != s.outputs.end();
    };
    std::vector<Slot*> order;
    for (auto& s : slots_)
        if (drives(s)) order.push_back(&s);
    for (auto& s : slots_)
        if (!drives(s)) order.push_back(&s);
    while (cursor < order.size()) {
        Slot& s = *order[cursor++];
        if (!s.adapter) continue;  // the software renderer has no decoder
        Gpu* g = Open(s);
        if (g && !g->Removed() && g->Decodes(v)) return g;
    }
    return nullptr;
}

Gpu* GpuSet::RendererFor(HMONITOR monitor) {
    std::lock_guard lock(mutex_);
    for (auto& s : slots_)
        if (s.adapter && std::find(s.outputs.begin(), s.outputs.end(), monitor) != s.outputs.end())
            if (Gpu* g = Open(s)) return g;
    for (auto& s : slots_)
        if (Gpu* g = Open(s)) return g;
    return nullptr;
}
